services:
    backup.command.create:
        class: BastSys\BackupBundle\Command\CreateBackupCommand
        arguments:
            - '@filesystem'
            - '%backup.directory%'
            - '%backup.maxBackups%'
            - '%backup.database%'
            - '%backup.filesDirectory%'
        tags:
            - console.command
